### PR TITLE
Added russian language for EU map

### PR DESCRIPTION
**Pull request by Bulbash3r**

### CODE REVIEW

**Review by blinchk — APPROVED** [review]

**Comment by blinchk** [comment]
@tenpages Looks, that translations PRs will be a lot in the near future. Maybe better to put 'em all to the external file?

**Comment by tenpages** [comment]
thanks. is it possible to further shorten the word for "pts"? It is currently still a little too long.

**Comment by Bulbash3r** [comment]
hi, @tenpages, I've changed short "очков - очк." to "единиц - ед.", both words are the same

**Comment by tenpages** [comment]
> hi, @tenpages, I've changed short "очков - очк." to "единиц - ед.", both words are the same

thanks. looks good now

**Pull request merged**
